/* preview-noindex.mjs — verifies the PREVIEW_MODE noindex gate.
 *
 * Boots server.js twice (with and without PREVIEW_MODE=1) and, using a custom
 * Host header, asserts:
 *   • Preview host + PREVIEW_MODE=1  → X-Robots-Tag on every response, robots
 *     meta on server-rendered entity HTML, robots.txt allows crawling but drops
 *     the Sitemap line, sitemap still reachable (just not advertised).
 *   • Production hosts stay indexable (no header, no meta, sitemap advertised) —
 *     both when PREVIEW_MODE is unset AND, as a safeguard, when it is mis-set.
 *   • Hostname normalization (case + :port) is applied before the host compare.
 *
 * Node built-ins only (child_process + http). Boots server.js from its own
 * directory, so it runs unchanged in the flat repo (seo-data.json committed) and
 * in the radiator-backend/ layout (seo-data.json generated by the build).
 *
 *   node tests/preview-noindex.mjs
 */
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import http from 'node:http';
import path from 'node:path';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');          // dir containing server.js
const PORT = process.env.PN_PORT || '8897';
const ROBOTS = 'noindex, nofollow, noarchive';

let pass = 0, fail = 0;
const ok = (c, name, extra = '') => { c ? pass++ : fail++; console.log(`${c ? 'PASS' : 'FAIL'} · ${name}${extra ? ' · ' + extra : ''}`); };

function startServer(extraEnv) {
  return spawn('node', ['server.js'], {
    cwd: ROOT,
    env: { ...process.env, PORT, MOCK: '1', ...extraEnv },
    stdio: ['ignore', 'ignore', 'inherit'],
  });
}
function stop(child) { try { child.kill('SIGKILL'); } catch {} }

// Raw http request so we control the Host header exactly (undici fetch forbids it).
function req(pathname, host) {
  return new Promise((resolve, reject) => {
    const r = http.request(
      { host: '127.0.0.1', port: Number(PORT), path: pathname, method: 'GET', headers: host ? { Host: host } : {} },
      res => { let body = ''; res.on('data', c => (body += c)); res.on('end', () => resolve({ status: res.statusCode, headers: res.headers, body })); }
    );
    r.on('error', reject); r.end();
  });
}
async function waitHealth(ms = 12000) {
  const t0 = Date.now();
  while (Date.now() - t0 < ms) {
    try { const r = await req('/api/health', 'radiator-preview.onrender.com'); if (r.status === 200 || r.status === 503) return true; } catch {}
    await new Promise(r => setTimeout(r, 200));
  }
  return false;
}
const xr = r => r.headers['x-robots-tag'];
const hasRobotsMeta = body => new RegExp(`<meta name="robots" content="${ROBOTS}">`).test(body);

const PREVIEW_HOST = 'radiator-preview.onrender.com';
const PROD_HOSTS = ['getradiator.com', 'www.getradiator.com', 'radiator-pkt6.onrender.com'];

// ============================================================================
// Process A — PREVIEW_MODE=1
// ============================================================================
{
  const srv = startServer({ PREVIEW_MODE: '1' });
  const up = await waitHealth();
  ok(up, '[preview] server boots with PREVIEW_MODE=1');

  // --- Case 1: preview host + PREVIEW_MODE=1 -------------------------------
  const home = await req('/', PREVIEW_HOST);
  ok(home.status === 200 && xr(home) === ROBOTS, 'case1 homepage → X-Robots-Tag noindex', 'xrt=' + xr(home));

  const bld = await req('/building/r0', PREVIEW_HOST);
  ok(bld.status === 200 && xr(bld) === ROBOTS, 'case1 building → 200 + X-Robots-Tag noindex', 'st=' + bld.status + ' xrt=' + xr(bld));
  ok(bld.status === 200 && hasRobotsMeta(bld.body), 'case1 building HTML → robots meta present');

  const firm = await req('/firm/fulton-grace', PREVIEW_HOST);
  ok(firm.status === 200 && xr(firm) === ROBOTS && hasRobotsMeta(firm.body), 'case1 firm → 200 + header + meta', 'st=' + firm.status);

  const api = await req('/api/health', PREVIEW_HOST);
  ok(xr(api) === ROBOTS, 'case1 API response → X-Robots-Tag noindex (every response)', 'xrt=' + xr(api));

  const robots = await req('/robots.txt', PREVIEW_HOST);
  ok(robots.status === 200 && /Allow: \//.test(robots.body) && !/Sitemap:/i.test(robots.body),
    'case1 robots.txt → allows crawling, NO Sitemap line', JSON.stringify(robots.body));

  const sm = await req('/sitemap.xml', PREVIEW_HOST);
  ok(sm.status === 200 && /<urlset/.test(sm.body), 'case1 sitemap.xml → still reachable for QA (just not advertised)', 'st=' + sm.status);

  // --- Case 5: normalization (mixed case + :port) still activates ----------
  const mixed = await req('/building/r0', 'RADIATOR-Preview.OnRender.COM:8080');
  ok(mixed.status === 200 && xr(mixed) === ROBOTS, 'case5 preview host with MixedCase + :port → still noindex (normalized)', 'xrt=' + xr(mixed));

  // --- Case 3 + 4: misconfig guard — prod hosts refuse even with the var ---
  for (const h of PROD_HOSTS) {
    const r = await req('/building/r0', h);
    ok(r.status === 200 && xr(r) === undefined && !hasRobotsMeta(r.body),
      `case3/4 prod host "${h}" + PREVIEW_MODE=1 → NO noindex (guard)`, 'xrt=' + xr(r));
    const rb = await req('/robots.txt', h);
    ok(/Sitemap:/i.test(rb.body), `case3/4 prod host "${h}" robots.txt still advertises sitemap`);
  }
  // Case 4: production host carrying an explicit port is still recognized as prod.
  const prodPort = await req('/building/r0', 'getradiator.com:443');
  ok(prodPort.status === 200 && xr(prodPort) === undefined,
    'case4 prod host with explicit :port → NO noindex (normalized then matched)', 'xrt=' + xr(prodPort));

  stop(srv);
  await new Promise(r => setTimeout(r, 300));
}

// ============================================================================
// Process B — PREVIEW_MODE unset (production's normal state)
// ============================================================================
{
  const srv = startServer({ PREVIEW_MODE: '' });
  const up = await waitHealth();
  ok(up, '[prod] server boots with PREVIEW_MODE unset');

  // --- Case 2: getradiator.com + unset → fully indexable ------------------
  const bld = await req('/building/r0', 'getradiator.com');
  ok(bld.status === 200 && xr(bld) === undefined && !hasRobotsMeta(bld.body),
    'case2 getradiator.com → 200, NO X-Robots-Tag, NO robots meta (indexable)', 'xrt=' + xr(bld));

  const robots = await req('/robots.txt', 'getradiator.com');
  ok(/Sitemap: https:\/\/getradiator\.com\/sitemap\.xml/.test(robots.body),
    'case2 getradiator.com robots.txt → advertises production sitemap', JSON.stringify(robots.body));

  // Primary protection: without PREVIEW_MODE, even the preview host is indexable.
  const prev = await req('/building/r0', PREVIEW_HOST);
  ok(prev.status === 200 && xr(prev) === undefined,
    'case2 preview host + PREVIEW_MODE unset → NO noindex (explicit var is the gate)', 'xrt=' + xr(prev));

  stop(srv);
}

console.log(`\nPREVIEW-NOINDEX RESULTS: ${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
